# Generated by Django 4.2.5 on 2023-10-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
