# Generated by Django 4.2.5 on 2023-10-10 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Quizzes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
    ]
