name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Create logs directory
        run: mkdir -p logs

      - name: Create .env file
        run: |
          cat <<EOL >> .env
          AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
          DEBUG=${{ secrets.DEBUG }}
          EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          EOL

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linter
        run: ruff check .

      - name: Wait for PostgreSQL to become ready
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "Postgres is up" && break
            echo "Waiting for Postgres..."
            sleep 1
          done

      - name: Run tests
        run: python manage.py test
        # env:
        #   AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        #   AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        #   AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        #   DEBUG: ${{ secrets.DEBUG }}
        #   EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        #   EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        #   POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        #   POSTGRES_HOST: localhost
        #   POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        #   POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        #   REDIS_HOST: ${{ secrets.REDIS_HOST }}
        #   REDIS_PORT: ${{ secrets.REDIS_PORT }}
        #   SECRET_KEY: ${{ secrets.SECRET_KEY }}
